<?php

declare(strict_types=1);

use App\Http\Controllers\CalendarController as ActivityCalendarController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\Portal\DashboardController as ClientPortalDashboardController;
use App\Http\Controllers\Portal\DdBusinessPlanController;
use App\Http\Controllers\Portal\EntrepreneurAssessmentController;
use App\Http\Controllers\Portal\EntrepreneurDashboardController;
use App\Http\Controllers\Portal\EntrepreneurGamificationController;
use App\Http\Controllers\Portal\EntrepreneurPlanController;
use App\Http\Controllers\Portal\EntrepreneurSurveyController;
use App\Http\Controllers\Portal\InspirationBoardController;
use App\Http\Controllers\Portal\MessageController;
use App\Http\Controllers\Portal\NpoBoardDashboardController;
use App\Http\Controllers\Portal\NpoImpactMetricController;
use App\Http\Controllers\Portal\OnboardingController;
use App\Http\Controllers\Portal\ProposalSignoffController;
use App\Http\Controllers\Portal\ReportController;
use App\Http\Controllers\Portal\ServiceActivationController;
use App\Http\Controllers\Portal\StrategicBudgetController;
use App\Http\Controllers\Portal\StrategicPlanMilestoneController;
use App\Http\Controllers\Portal\SurveyController;
use App\Http\Controllers\Portal\WellbeingController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'verified', 'mfa'])
    ->prefix('portal')
    ->name('portal.')
    ->group(function (): void {
        Route::get('/', ClientPortalDashboardController::class)->name('dashboard');
        Route::redirect('strategic-plan-budget', 'business-plan-budget');
        Route::get('business-plan-budget', [StrategicBudgetController::class, 'show'])->name('business-plan-budget.show');
        Route::post('business-plan-budget', [StrategicBudgetController::class, 'update'])->name('business-plan-budget.update');
        Route::post('business-plan-budget/submit', [StrategicBudgetController::class, 'submit'])->name('business-plan-budget.submit');
        Route::get('business-plan-budget/export', [StrategicBudgetController::class, 'export'])->name('business-plan-budget.export');
        Route::patch('strategic-plan/milestones/{milestone}', [StrategicPlanMilestoneController::class, 'update'])->name('strategic-plan.milestones.update');
        Route::get('service-activations/new/{serviceType}', [ServiceActivationController::class, 'create'])->name('service-activations.create');
        Route::post('service-activations', [ServiceActivationController::class, 'store'])->name('service-activations.store');
        Route::get('service-activations/{serviceActivation}', [ServiceActivationController::class, 'show'])->name('service-activations.show');
        Route::post('service-activations/{serviceActivation}/payment-complete', [ServiceActivationController::class, 'paymentComplete'])->name('service-activations.payment-complete');
        Route::post('service-activations/{serviceActivation}/accept', [ServiceActivationController::class, 'accept'])->name('service-activations.accept');
        Route::get('npo-board', NpoBoardDashboardController::class)->name('npo-board.dashboard');
        Route::get('calendar', ActivityCalendarController::class)->name('calendar.index');
        Route::get('acquisition-plan', [DdBusinessPlanController::class, 'show'])->name('dd-plan.show');
        Route::get('acquisition-plan/preview', [DdBusinessPlanController::class, 'preview'])->name('dd-plan.preview');
        Route::post('acquisition-plan', [DdBusinessPlanController::class, 'store'])->name('dd-plan.store');
        Route::post('acquisition-plan/sections', [DdBusinessPlanController::class, 'section'])->name('dd-plan.sections.store');
        Route::post('acquisition-plan/sections/{planSection}/guidance', [DdBusinessPlanController::class, 'guidance'])->name('dd-plan.sections.guidance');
        Route::post('acquisition-plan/complete', [DdBusinessPlanController::class, 'complete'])->name('dd-plan.complete');
        Route::post('acquisition-plan/business-advice', [DdBusinessPlanController::class, 'requestAdvice'])->name('dd-plan.business-advice.store');
        Route::get('entrepreneur', EntrepreneurDashboardController::class)->name('entrepreneur.dashboard');
        Route::get('entrepreneur/plan', [EntrepreneurPlanController::class, 'show'])->name('entrepreneur.plan.show');
        Route::get('entrepreneur/plan/preview', [EntrepreneurPlanController::class, 'preview'])->name('entrepreneur.plan.preview');
        Route::post('entrepreneur/readiness', [EntrepreneurPlanController::class, 'readiness'])->name('entrepreneur.readiness.store');
        Route::post('entrepreneur/idea-validation', [EntrepreneurPlanController::class, 'ideaValidation'])->name('entrepreneur.idea-validation.store');
        Route::post('entrepreneur/plan/start', [EntrepreneurPlanController::class, 'start'])->name('entrepreneur.plan.start');
        Route::post('entrepreneur/plan/requirements/assist', [EntrepreneurPlanController::class, 'assistRequirement'])->name('entrepreneur.plan.requirements.assist');
        Route::post('entrepreneur/plan/sections', [EntrepreneurPlanController::class, 'section'])->name('entrepreneur.plan.sections.store');
        Route::post('entrepreneur/plan/sections/{planSection}/guidance', [EntrepreneurPlanController::class, 'guidance'])->name('entrepreneur.plan.sections.guidance');
        Route::post('entrepreneur/plan/budget', [EntrepreneurPlanController::class, 'budget'])->name('entrepreneur.plan.budget.update');
        Route::get('entrepreneur/plan/budget-pack', [EntrepreneurPlanController::class, 'budgetPack'])->name('entrepreneur.plan.budget-pack.show');
        Route::get('entrepreneur/plan/budget-pack/pdf', [EntrepreneurPlanController::class, 'budgetPackPdf'])->name('entrepreneur.plan.budget-pack.pdf');
        Route::post('entrepreneur/plan/budget/flags/acknowledge', [EntrepreneurPlanController::class, 'acknowledgeBudgetFlag'])->name('entrepreneur.plan.budget.flags.acknowledge');
        Route::post('entrepreneur/plan/budget/advisor-nudge/dismiss', [EntrepreneurPlanController::class, 'dismissBudgetAdvisorNudge'])->name('entrepreneur.plan.budget.advisor-nudge.dismiss');
        Route::post('entrepreneur/plan/submit', [EntrepreneurPlanController::class, 'submit'])->name('entrepreneur.plan.submit');
        Route::post('entrepreneur/advisory-request', [EntrepreneurPlanController::class, 'requestAdvisory'])->name('entrepreneur.advisory-request.store');
        Route::post('entrepreneur/gamification/disable-request', [EntrepreneurGamificationController::class, 'requestDisable'])->name('entrepreneur.gamification.disable-request');
        Route::post('entrepreneur/gamification/seen', [EntrepreneurGamificationController::class, 'seen'])->name('entrepreneur.gamification.seen');
        Route::get('entrepreneur/assessments/{planAssessment}', [EntrepreneurAssessmentController::class, 'show'])->name('entrepreneur.assessments.show');
        Route::get('entrepreneur/surveys', [EntrepreneurSurveyController::class, 'index'])->name('entrepreneur.surveys.index');
        Route::get('entrepreneur/surveys/{surveyAssignment}', [EntrepreneurSurveyController::class, 'show'])->name('entrepreneur.surveys.show');
        Route::post('entrepreneur/surveys/{surveyAssignment}', [EntrepreneurSurveyController::class, 'submit'])->name('entrepreneur.surveys.submit');
        Route::post('documents', DocumentController::class)->name('documents.store');
        Route::get('documents/{document}', [DocumentController::class, 'show'])->name('documents.show');
        Route::get('reports/{report}', [ReportController::class, 'show'])->name('reports.show');
        Route::post('npo-impact-metrics', NpoImpactMetricController::class)->name('npo-impact-metrics.store');
        Route::get('inspiration-board', [InspirationBoardController::class, 'index'])->name('inspiration-board.index');
        Route::get('inspiration-board/{boardPost}/image', [InspirationBoardController::class, 'image'])->name('inspiration-board.image');
        Route::get('messages', [MessageController::class, 'index'])->name('messages.index');
        Route::post('messages', [MessageController::class, 'store'])->name('messages.store');
        Route::get('messages/{messageThread}', [MessageController::class, 'show'])->name('messages.show');
        Route::post('messages/{messageThread}', [MessageController::class, 'reply'])->name('messages.reply');
        Route::get('proposals/{proposal}', [ProposalSignoffController::class, 'viewProposal'])->name('proposals.show');
        Route::get('proposals/{proposal}/download', [ProposalSignoffController::class, 'download'])->name('proposals.download');
        Route::get('proposals/{proposal}/signoff', [ProposalSignoffController::class, 'show'])->name('proposals.signoff.show');
        Route::post('proposals/{proposal}/signoff/payment-setup', [ProposalSignoffController::class, 'paymentSetup'])->name('proposals.signoff.payment-setup');
        Route::post('proposals/{proposal}/signoff/{step}', [ProposalSignoffController::class, 'step'])->name('proposals.signoff.step');
        Route::get('wellbeing', [WellbeingController::class, 'show'])->name('wellbeing.show');
        Route::post('wellbeing', [WellbeingController::class, 'store'])->name('wellbeing.store');
        Route::delete('wellbeing/{wellbeingCheckin}', [WellbeingController::class, 'destroy'])->name('wellbeing.destroy');
        Route::get('surveys', [SurveyController::class, 'index'])->name('surveys.index');
        Route::get('surveys/{surveyAssignment}', [SurveyController::class, 'show'])->name('surveys.show');
        Route::post('surveys/{surveyAssignment}', [SurveyController::class, 'submit'])->name('surveys.submit');
        Route::get('onboarding', [OnboardingController::class, 'redirect'])->name('onboarding.index');
        Route::get('onboarding/{step}', [OnboardingController::class, 'show'])->name('onboarding.step');
        Route::post('onboarding/{step}', [OnboardingController::class, 'store'])->name('onboarding.store');
    });
